### ISSUE TITLE
IE Crate eats up items

### ISSUE THREAD

**Issue by Klebestreifen** [MasterEnderman/Zerblands-Remastered#74]
I found a bug where items disappear out of a Wooden Storage Crate.

I had items in a Wooden Storage Crate (Immersive Engineering), took it in my inventory and sorted my inventory.
As I placed the crate I realized it was empty.

I tried some stuff but this only happens when sorting my inventory with middle click.

On behalf of Merry.

**Comment by MasterEnderman** [comment]
Fixed with the newest update to Inventory Bogo Sort.
