### ISSUE TITLE
Ectoplasma seems too difficult

### ISSUE THREAD

**Issue by chloecat34** [MasterEnderman/Zerblands-Remastered#84]
How is the player supposed to get enough Ectoplasm to make Ectoplasma for stuff like Spectre String? It requires 1000 mb per craft, but melting Ectoplasm only makes 10 mb. Do you just need to set up a spirit spawner and kill them with magic? It seems a bit extreme to need 100 Ectoplasm per Spectre String, especially since Spectre String is used for Fluxed String for Dense ME Cables.

**Comment by chloecat34** [comment]
This is specifically in Nightmare Mode btw

**Comment by MasterEnderman** [comment]
@milesman34 sorry for the late answer. once you obtain some ectoplasma from a spirit you can righ-click it on a (vanilla) sapling to create a spectre tree, which can be harvested for more ectoplasma. this process can also be automated as it drops spectre saplings.
The reason it only gives 10mb is, that setting up a farm for a tree isn't really hard to accomplish.
[Link to the Random Things Wiki](https://lumien.net/rtwiki/blocks/spectre-sapling/)

**Comment by MasterEnderman** [comment]
with version 2.2.0 (waits for approval by curseforge) i also increased the amount of ectoplasm from 10 to 50 mb per item.
